<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Ticketing.Domain\Ticketing.Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="Shouldly" />
    </ItemGroup>
    <ItemGroup>
        <Using Include="Xunit" />
        <Using Include="Shouldly" />
    </ItemGroup>
</Project>
