<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\Ticketing.Domain\Ticketing.Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="Ticketing.Application.Tests" />
    </ItemGroup>
</Project>
